apiVersion: apps/v1
kind: Deployment
metadata:
  name: conciliacion
  namespace: conciliacion-v1
  labels:
    app: conciliacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conciliacion
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: conciliacion
    spec:
      containers:
        - name: conciliacion
          image: 243616138453.dkr.ecr.us-east-2.amazonaws.com/grupo1:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080