apiVersion: v1
kind: Service
metadata:
  name: conciliacion
  namespace: conciliacion-v1
spec:
  selector:
    app: conciliacion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP