server:
  port: 8080
  servlet:
    context-path: /conciliacion
spring:
  application:
    name: conciliacion
  main:
    banner-mode: "off"
  jmx:
    enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://dbprd01.ctpsywmohtj4.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgre
    password: Muylargo1
    driver-class-name: org.postgresql.Driver